### ISSUE TITLE
Add video structured data on the individual video pages

### ISSUE THREAD

**Issue by deshetti** [factly/dega-themes#3]
@mhjadav Lets discuss this on the call. We need to add structured data for the video pages like mentioned here: https://developers.google.com/search/docs/data-types/video#type-definitions

**Comment by mhjadav** [comment]
Add structured data for below pages - 

1. https://gatsby-theme-factly.onrender.com/videos/
2. https://gatsby-theme-factly.onrender.com/degacms_factcheck/factcheckinggovernmentclaimsoninitiativesrelatedtoagriculturepart2
3. https://gatsby-theme-factly.onrender.com/degacms_post/political-contributions-by-yes-bank-defaulter-groups
4. https://gatsby-theme-factly.onrender.com/playlist/PLEQcsVYyf3IBYqmtPuCp2b_6XMdTG52MQ?v=u8Zj09qJPXQ

**Comment by deshetti** [comment]
@mhjadav I am not sure if you are aware, but you could test the structured data using Google's structured data testing tools: https://search.google.com/structured-data/testing-tool/u/0/

I see that there are bunch of errors when I tested no. 2 in the above list. Please check and rectify the errors.
